name: s2gm
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - blas=1.0
  - bokeh=0.13.0
  - boost-cpp=1.68.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates
  - cairo=1.16.0
  - cairosvg=2.4.2
  - certifi=2018.8.24
  - cffi=1.11.5
  - cftime=1.0.1
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=0.6.1
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - cssselect2=0.2.1
  - curl=7.63.0
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=0.19.2
  - dask-core=0.19.2
  - defusedxml=0.6.0
  - distributed=1.23.2
  - expat=2.2.5
  - freetype=2.9.1
  - freexl=1.0.5
  - gdal=2.2.2
  - geos=3.6.2
  - geotiff=1.4.2
  - h5netcdf=0.6.2
  - h5py=2.7.1
  - hdf4=4.2.13
  - hdf5=1.10.1
  - heapdict=1.0.0
  - html5lib=1.0.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.7
  - intel-openmp=2019.1
  - jinja2=2.10.3
  - jpeg=9c
  - kealib=1.4.7
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - libcurl=7.63.0
  - libgdal=2.2.2
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.4.1.1
  - libpng=1.6.36
  - libpq=10.6
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libxml2=2.9.8
  - locket=0.2.0
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mkl=2018.0.3
  - mkl_fft=1.0.9
  - mkl_random=1.0.1
  - msgpack-python=0.5.6
  - msys2-conda-epoch=20160418
  - netcdf4=1.3.1
  - numpy=1.15.2
  - numpy-base=1.15.2
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.0.2p
  - packaging=19.0
  - pandas=0.23.4
  - partd=0.3.9
  - patsy=0.5.1
  - pcre=8.41
  - pillow=5.3.0
  - pip=18.0
  - pixman=0.38.0
  - postgresql=10.6
  - proj4=4.9.3
  - psutil=5.4.7
  - pycparser=2.19
  - pyopenssl=18.0.0
  - pyparsing=2.3.1
  - pyphen=0.9.5
  - pyqt=5.6.0
  - pyreadline=2.1
  - pysocks=1.6.8
  - python=3.5.5
  - python-dateutil=2.7.5
  - pytz=2018.9
  - pyyaml=3.13
  - qt=5.6.2
  - requests=2.19.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=40.4.3
  - sip=4.18.1
  - six=1.11.0
  - sortedcontainers=2.1.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tbb=2020.1
  - tbb4py=2019.1
  - tblib=1.3.2
  - tinycss2=1.0.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=5.1.1
  - urllib3=1.23
  - vc=14
  - vs2015_runtime=14.0.25420
  - webencodings=0.5.1
  - wheel=0.32.0
  - win_inet_pton=1.0.1
  - wincertstore=0.2
  - xarray=0.10.9
  - xerces-c=3.2.0
  - xz=5.2.4
  - yaml=0.1.7
  - zict=0.1.3
  - zlib=1.2.11
  - zstd=1.3.3
  - pip:
    - cairocffi==1.0.1
    - weasyprint==44